version: '3.8'

services:
  postgres-mcp-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://svc_readonly:your_password@your_db_host:25060/your_database?sslmode=require
      - AUTH_TOKEN=your-secure-bearer-token-here
      - MAX_ROWS=1000
      - QUERY_TIMEOUT=30
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: NGINX reverse proxy with HTTPS
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - postgres-mcp-server
    restart: unless-stopped